name: example
description: A sample command-line application as an example for kiwi.
version: 0.1.0
homepage: https://github.com/vanlooverenkoen/kiwi

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  kiwi: ^4.0.1

dev_dependencies:
  test: ^1.20.1
  build_runner: ^2.1.7
  kiwi_generator: ^4.0.1

dependency_overrides:
  kiwi:
    path: ../kiwi
  kiwi_generator:
    path: ../kiwi_generator