name: kiwi_generator
description: Generates dependency injection code using the kiwi package to reduce development time.
version: 4.2.1
homepage: https://github.com/gbtb16/kiwi/tree/master/packages/kiwi_generator
repository: https://github.com/gbtb16/kiwi/tree/master/packages/kiwi_generator
issue_tracker: https://github.com/gbtb16/kiwi/issues

environment:
  sdk: '>=2.14.0 <4.0.0'

dependencies:
  analyzer: ^6.0.0
  build: ^2.4.1
  build_config: ^1.1.1
  built_collection: ^5.1.1
  code_builder: ^4.10.0
  dart_style: ^2.2.4
  kiwi: ^5.0.1
  path: ^1.8.3
  source_gen: ^1.5.0

dev_dependencies:
  build_runner: ^2.3.3
  build_test: ^2.1.6
  test: ^1.25.1

topics:
  - kiwi
  - automatic-generator
  - dependency-injector