name: kiwi_generator
description: Generates dependency injection code using the kiwi package to reduce development time.
version: 4.0.0
homepage: https://github.com/vanlooverenkoen/kiwi/tree/master/kiwi_generator

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  analyzer: ^2.6.0
  build: ^2.1.1
  build_config: ^1.0.0
  code_builder: ^4.1.0
  dart_style: ^2.2.0
  kiwi: ^4.0.0
  path: ^1.8.0
  source_gen: ^1.1.1
  built_collection: ^5.1.1

dev_dependencies:
  build_runner: ^2.1.4
  build_test: ^2.1.4
  test: ^1.18.2

dependency_overrides:
  kiwi:
    path: ../kiwi