name: kiwi_generator
description: Generates dependency injection code using the kiwi package to reduce development time.
version: 4.0.3
homepage: https://github.com/vanlooverenkoen/kiwi/tree/master/kiwi_generator

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  analyzer: ^5.1.0
  build: ^2.3.1
  build_config: ^1.1.1
  code_builder: ^4.3.0
  dart_style: ^2.2.4
  kiwi: ^4.0.3
  path: ^1.8.2
  source_gen: ^1.2.6
  built_collection: ^5.1.1

dev_dependencies:
  build_runner: ^2.3.2
  build_test: ^2.1.5
  test: ^1.21.6

dependency_overrides:
  kiwi:
    path: ../kiwi