name: kiwi_generator
description: Generates dependency injection code using the kiwi package to reduce development time.
version: 4.0.2
homepage: https://github.com/vanlooverenkoen/kiwi/tree/master/kiwi_generator

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  analyzer: ^3.2.0
  build: ^2.2.1
  build_config: ^1.0.0
  code_builder: ^4.1.0
  dart_style: ^2.2.1
  kiwi: ^4.0.1
  path: ^1.8.0
  source_gen: ^1.2.1
  built_collection: ^5.1.1

dev_dependencies:
  build_runner: ^2.1.7
  build_test: ^2.1.5
  test: ^1.20.1

dependency_overrides:
  kiwi:
    path: ../kiwi