name: kiwi_generator
description: Generates dependency injection code using the kiwi package to reduce development time.
version: 0.3.0
author: Romain Rastel <lets4r@gmail.com>
homepage: https://github.com/letsar/kiwi

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:  
  analyzer: '>= 0.32.4 <0.35.0'
  build: '>=0.12.6 <1.2.0'
  build_config: ^0.3.1
  code_builder: ^3.1.3
  dart_style: '>= 1.0.0 <1.3.0'
  kiwi: '>=0.1.0 <0.2.0'
  path: ^1.6.2
  source_gen: ^0.9.1

dev_dependencies:
  build_runner: ^1.1.0
  build_test: ^0.10.3
  test: ^1.0.0
