name: dart_kiwi_example

on:
  push:
    branches: [ 'master', 'stable' ]
  pull_request:
    branches: [ 'master', 'stable' ]

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: examples/dart_kiwi
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2.16.0
        with:
          channel: 'stable'
      - run: flutter packages get
      - run: flutter analyze
      - run: dart format -o none --set-exit-if-changed .
